---

all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: "{{ SSH_PRIVATE_KEY }}"

    installation_method: archive
    confluent_archive_file_source: https://packages.confluent.io/archive/7.4/confluent-7.4.0.tar.gz

    #### Monitoring Configuration ####
    jmxexporter_enabled: "true"
    jolokia_enabled: "true"

kafka_controller:
  hosts:
    <kraft-host-1>:
    <kraft-host-2>:
    <kraft-host-3>:

kafka_broker:
  hosts:
    <kafka-broker-host-1>:
    <kafka-broker-host-2>:
    <kafka-broker-host-3>:

schema_registry:
  hosts:
    <sr-host>:

control_center:
  hosts:
    <c3-host>: